# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Kapil Arora
tagline:          'Cloud Platform Architect'
description1:     'Cloud, Devops and Storage'
description2:     'Architect | Developer | Blogger'
url:              
baseurl:          /

author:
  name:           'Kapil Arora'
  url:            kapilarora.de

paginate:         10

# Custom vars
version:          2.1.0

github: kapilarora          
linkedin: kaparora
twitter: kaparora
# Gems
gems: [jekyll-paginate]
